myDirectory: 
  Type: AWS::DirectoryService::MicrosoftAD
  Properties: 
    Name: "vattigunta.com"
    Password: 
      Ref: MicrosoftADPW
    ShortName: 
      Ref: MicrosoftADShortName
    VpcSettings: 
      SubnetIds: 
        - Ref: subnetID1
        - Ref: subnetID2
      VpcId: 
        Ref: vpcID
